"""add image_type to product_images

Revision ID: 74043ebcfae5
Revises: 3b89398f2e9c
Create Date: 2026-08-26 18:32:19.128296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74043ebcfae5'
down_revision: Union[str, Sequence[str], None] = '3b89398f2e9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        'product_images',
        sa.Column(
            'image_type',
            sa.String(length=20),
            nullable=True
        )
    )

    op.execute("""
        UPDATE product_images
        SET image_type = 'gallery'
        WHERE image_type IS NULL
    """)

    op.alter_column(
        'product_images',
        'image_type',
        nullable=False
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_images', 'image_type')
    # ### end Alembic commands ###
