"""add timestamps admin_users

Revision ID: 759770184887
Revises: e45b51aea86b
Create Date: 2026-09-02 18:30:12.974225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '759770184887'
down_revision: Union[str, Sequence[str], None] = 'e45b51aea86b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_users', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('admin_users', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_constraint(op.f('admin_users_email_key'), 'admin_users', type_='unique')
    op.create_index(op.f('ix_admin_users_email'), 'admin_users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_admin_users_email'), table_name='admin_users')
    op.create_unique_constraint(op.f('admin_users_email_key'), 'admin_users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_column('admin_users', 'updated_at')
    op.drop_column('admin_users', 'created_at')
    # ### end Alembic commands ###
