"""create admin users

Revision ID: da8df6ae41db
Revises: 1e461beb59ee
Create Date: 2026-08-30 03:02:32.442096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da8df6ae41db'
down_revision: Union[str, Sequence[str], None] = '1e461beb59ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_images', 'is_primary')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_images', sa.Column('is_primary', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
