"""add product dimensions

Revision ID: e45b51aea86b
Revises: f0f1f385fac3
Create Date: 2026-08-31 16:52:02.600502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e45b51aea86b'
down_revision: Union[str, Sequence[str], None] = 'f0f1f385fac3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():

    op.add_column(
        'products',
        sa.Column(
            'weight',
            sa.Numeric(10, 3),
            nullable=False,
            server_default='0.1'
        )
    )

    op.add_column(
        'products',
        sa.Column(
            'height',
            sa.Integer(),
            nullable=False,
            server_default='1'
        )
    )

    op.add_column(
        'products',
        sa.Column(
            'width',
            sa.Integer(),
            nullable=False,
            server_default='1'
        )
    )

    op.add_column(
        'products',
        sa.Column(
            'length',
            sa.Integer(),
            nullable=False,
            server_default='1'
        )
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'length')
    op.drop_column('products', 'width')
    op.drop_column('products', 'height')
    op.drop_column('products', 'weight')
    # ### end Alembic commands ###
