"""add order customer address

Revision ID: f0f1f385fac3
Revises: c85e7d7c6992
Create Date: 2026-08-30 03:43:35.965858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0f1f385fac3'
down_revision: Union[str, Sequence[str], None] = 'c85e7d7c6992'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('customer_cpf', sa.String(length=14), nullable=False))
    op.add_column('orders', sa.Column('cep', sa.String(length=9), nullable=False))
    op.add_column('orders', sa.Column('street', sa.String(length=255), nullable=False))
    op.add_column('orders', sa.Column('number', sa.String(length=20), nullable=False))
    op.add_column('orders', sa.Column('complement', sa.String(length=255), nullable=True))
    op.add_column('orders', sa.Column('neighborhood', sa.String(length=255), nullable=False))
    op.add_column('orders', sa.Column('city', sa.String(length=255), nullable=False))
    op.add_column('orders', sa.Column('state', sa.String(length=2), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'state')
    op.drop_column('orders', 'city')
    op.drop_column('orders', 'neighborhood')
    op.drop_column('orders', 'complement')
    op.drop_column('orders', 'number')
    op.drop_column('orders', 'street')
    op.drop_column('orders', 'cep')
    op.drop_column('orders', 'customer_cpf')
    # ### end Alembic commands ###
